apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
      - name: classificacao
        image: felpe000/classificacao
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  #nome diferente do outro de tipo NodePort
  #que hav√≠amos criado
  name: classificacao-clusterip-service
spec:
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000
