apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
      - name: consulta
        image: felpe000/consulta
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  #nome diferente do outro de tipo NodePort
  #que hav√≠amos criado
  name: consulta-clusterip-service
spec:
  type: NodePort
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000
