apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
      - name: observacoes
        image: felpe000/observacoes
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  #nome diferente do outro de tipo NodePort
  #que hav√≠amos criado
  name: observacoes-clusterip-service
spec:
  type: NodePort
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000
